In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("data.csv")

In [6]:
data.head()

,id,pol_bonus,pol_coverage,pol_duration,pol_sit_duration,pol_pay_freq,pol_payd,pol_usage,pol_insee_code,drv_drv2,...,vh_weight,town_mean_altitude,town_surface_area,population,lat_long_town,commune_code,canton_code,city_district_code,regional_department_code,claim_amount
0,A00048679_V01,0.50,Maxi,21,2,Monthly,No,Retired,64483,No,...,790,31.0,1950.0,13.7,"43.3947886873, -1.63099021573",483.0,34.0,1.0,64,0.0
1,A00036855_V01,0.50,Maxi,19,4,Monthly,No,Retired,56220,No,...,1120,6.0,1065.0,1.1,"47.7172153555, -3.18492247934",220.0,28.0,1.0,56,0.0
2,A00051293_V01,0.51,Median2,5,1,Yearly,No,WorkPrivate,14106,No,...,2210,38.0,482.0,0.7,"49.2360824637, -0.221042310396",106.0,47.0,2.0,14,0.0
3,A00054760_V01,0.50,Maxi,26,1,Monthly,No,Retired,34258,No,...,1141,96.0,936.0,1.4,"43.4689118509, 3.17497763189",258.0,25.0,1.0,34,0.0
4,A00077495_V01,0.50,Median2,5,2,Yearly,No,WorkPrivate,24064,No,...,0,147.0,3620.0,2.1,"45.360114867, 0.65590360604",64.0,4.0,3.0,24,0.0

In [8]:
data.describe()

,pol_bonus,pol_duration,pol_sit_duration,drv_age1,drv_age2,drv_age_lic1,drv_age_lic2,vh_age,vh_cyl,vh_din,...,vh_speed,vh_value,vh_weight,town_mean_altitude,town_surface_area,population,commune_code,canton_code,city_district_code,claim_amount
count,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,15999.000000,16000.000000,16000.000000,...,16000.000000,16000.000000,16000.000000,15887.000000,15887.000000,15887.000000,15887.000000,15887.000000,15887.000000,16000.000000
mean,0.536357,11.143000,2.751125,54.800063,15.685375,32.579313,9.187188,9.695418,1641.898875,90.792250,...,170.441563,17916.797000,1121.280750,175.915969,2489.780324,34.594442,219.834456,43.083276,2.392270,106.387764
std,0.096745,8.558651,2.375140,14.865985,24.124951,13.473727,17.056325,7.137755,457.950580,33.916196,...,23.347870,8545.221007,358.920755,223.083827,2920.886063,64.474778,173.026375,34.440031,1.406612,480.666492
min,0.500000,1.000000,1.000000,19.000000,0.000000,1.000000,0.000000,1.000000,425.000000,15.000000,...,75.000000,648.000000,0.000000,0.000000,68.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,0.500000,4.000000,1.000000,44.000000,0.000000,22.000000,0.000000,4.000000,1360.000000,68.000000,...,157.000000,11950.000000,950.000000,46.000000,837.500000,1.900000,81.000000,16.000000,1.000000,0.000000
50%,0.500000,9.000000,2.000000,55.000000,0.000000,33.000000,0.000000,8.000000,1587.000000,86.000000,...,170.000000,16130.000000,1120.000000,106.000000,1595.000000,7.700000,181.000000,31.000000,2.000000,0.000000
75%,0.500000,17.000000,3.000000,65.000000,34.000000,43.000000,15.000000,13.000000,1905.000000,109.000000,...,185.000000,22000.000000,1320.000000,219.000000,3146.500000,35.300000,315.000000,88.000000,3.000000,0.000000
max,1.560000,39.000000,25.000000,100.000000,97.000000,111.000000,111.000000,63.000000,6332.000000,507.000000,...,310.000000,145000.000000,3500.000000,2583.000000,75821.000000,440.200000,908.000000,99.000000,9.000000,11724.250000

In [16]:
clean_data = data[['drv_age1', 'drv_age_lic1', 'vh_age', 'vh_value', 'vh_speed']]

In [30]:
np.where(clean_data['vh_age'].isnull())

(array([414], dtype=int64),)